### ISSUE TITLE
parsePlaylistEntries is broken (vlc 4.0)

### ISSUE THREAD

**Issue by Andy1210** [alexandrucancescu/node-vlc-client#7]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `vlc-client@1.1.1` for the project I'm working on.

I am using vlc 4.0 nightly builds, so maybe the difference is coming from that. The diff is obviously for the dist file, but you got the idea. If you think this is indeed a necessary fix, I can create a normal PR, if it's relevant for vlc 4.0 only, then I can make it backward compatible as well.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/vlc-client/dist/Client.js b/node_modules/vlc-client/dist/Client.js
index a9e1674..0f5c2e2 100644
--- a/node_modules/vlc-client/dist/Client.js
+++ b/node_modules/vlc-client/dist/Client.js
@@ -593,9 +593,7 @@ class Client {
     }
     static parsePlaylistEntries(buffer) {
         const playlistResponse = JSON.parse(buffer.toString());
-        return playlistResponse.children
-            .find(c => c.name === "Playlist")
-            .children
+        return playlistResponse
             .map(pe => ({
             id: pe.id,
             name: pe.name,
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by alexandrucancescu** [comment]
Can you explain exactly what is not working when using the nightly build?

**Comment by Andy1210** [comment]
As you can see in the diff I posted above, there the response is already the playlist and you don't need to filter for it.

**Comment by normen** [comment]
+1 for this one, when trying to grab a playlist you get this error:
```
TypeError: Cannot read properties of undefined (reading 'children')
    at Client.parsePlaylistEntries (/Users/normenhansen/Dev/NodeCode/test-vlc/node_modules/vlc-client/dist/Client.js:598:13)
    at Client.<anonymous> (/Users/normenhansen/Dev/NodeCode/test-vlc/node_modules/vlc-client/dist/Client.js:523:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/normenhansen/Dev/NodeCode/test-vlc/node_modules/vlc-client/dist/Client.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.1.0
```

Edit: Sorry, I misinterpreted - this error is due to the fact that in the german version of VLC the playlist if called `Wiedergabeliste` and this library searches by name...
